### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by aleksasiriski** [nikatar/egress-cilium-node-ha-operator#2]
Please consider adding a license like MIT or Apache, currently this project is proprietery.

**Comment by nikatar** [comment]
Added gpl3 license

**Comment by kranich** [comment]
@nikatar Could you please consider switching to a non-copyleft license like MIT or Apache? GPL3 makes it harder to use your solution in corporate contexts.

**Comment by aleksasiriski** [comment]
+1 for a more Enterprise friendly license, don't really see the point for using GPL for this kind of project. MIT, Apache or MPL could work nicely since a lot of enterprises just discard using GPL and derivatives when the project is a small one.
